### ISSUE TITLE
Everyone involved in or supporting this project is a fucked up little weirdo

### ISSUE THREAD

**Issue by horse-mans** [domgetter/NCoC#11]
n/t

**Comment by wareya** [comment]
Inferiority complex?

**Comment by OKNoah** [comment]
what a surprise, it's 3 white males.

**Comment by sinistersnare** [comment]
If you want to have an actual conversation about the merits of this project, then please offer your arguments. Otherwise, why are you being just as rude and offensive as the people who want CoCs?

**Comment by horse-mans** [comment]
lol just lol if u think this project has merits

also there's no code of conduct so I can say whatever I want about this project, including the verifiable fact that its supporters are sad little people, and you can't do anything about it

**Comment by sinistersnare** [comment]
spam requires no code of conduct. you have opened up multiple issues that exist solely as spam.

**Comment by wareya** [comment]
>also there's no code of conduct so I can say whatever I want

That is literally just not true at all. Github itself has terms of use.

**Comment by horse-mans** [comment]
and it would be completely antithetical to this project to adhere to them ;-)

**Comment by wareya** [comment]
Maybe if you have no concept of precedence
