### ISSUE TITLE
the authors of the No Code of Conduct thing are incapable of love

### ISSUE THREAD

**Issue by horse-mans** [domgetter/NCoC#12]
not really a code issue but figured id point it out, because it's super obvious and permeates every word and sentence in this sad little repo

suggested fix:
open up your heart, remember what the word community means, realize that not everyone is like you, and that as community members you have a duty to protect those unable to protect themselves by virtue of sex, illness, race, mental health, or disposition

**Comment by wareya** [comment]
O irony

**Comment by sinistersnare** [comment]
@wareya, id sugget not responding and instead reporting him for spamming.

https://github.com/contact?report=horse-mans

**Comment by horse-mans** [comment]
if you report me you're a snitch and you'll have proven you actually don't believe in not having a code of conduct

**Comment by horse-mans** [comment]
hmm this guy is being mean on a project where we assert that anything goes on projects like this. time to baw to the nearest authority
