### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by bdistin** [domgetter/NCoC#20]
While you give explicit permission to: `Simply copy CODE_OF_CONDUCT.md into the root directory of your project. You may modify it to your needs.` in your readme, typically when a project does not include a license full copy protection is implied.

I suggest adding a License with similar terms added to the repo, so that I and others feel comfortable making use of your work. The [Unlicense](http://unlicense.org/) fits your statement in the readme. But ultimately it's up to you which to choose. (I could also see this project wanting a license that maintains the link-back attribution, which wouldn't be covered with Unlicense...)

**Comment by bdistin** [comment]
6 month bump

**Comment by domgetter** [comment]
Added Unlicense.  Thanks @bdistin
