### ISSUE TITLE
Contradictory Name

### ISSUE THREAD

**Issue by lil5** [domgetter/NCoC#27]
Personally the NoCoC feels counter to it's name. 

Especially under the Answers specifying banning.

**Comment by SilicaAndPina** [comment]
yes i thought the same.. xD

not a fan of banning "mobsters" or whatever feel like it can be abused lol
if you want no CoC why not just put nothing there for a CoC at all?

**Comment by david0178418** [comment]
It's the difference between an explicit "no" vs a non-answer to a question.

**Comment by lil5** [comment]
@david0178418 but from what I see the NoCoC isn't that either (see #28)

**Comment by Karunamon** [comment]
I see the second hard thing in computer science has reared its ugly head :)

The whole point here is that "code of conduct" in the open source world universally means this stifling, easily-abused document meant to be used as an ideological cudgel. The NCoC takes the opposite approach of saying that entire concept is crap, we're all adults here, nothing else matters.

Kinda like how the GPL is still a license.

**Comment by domgetter** [comment]
Then it will remain contradictory, like "logical fallacies" and "criminal justice".
