### ISSUE TITLE
Code of Conduct is in the Readme

### ISSUE THREAD

**Issue by lil5** [domgetter/NCoC#28]
I'm puzzled why the NoCoC is in the Readme and not in the CodeOfConduct file.

Or is the Readme purely a statement showing the reasoning for making a blank CoC?

**Comment by Karunamon** [comment]
The readme is the full explanation with details and FAQs. The actual NCoC consists of the words:

"This project adheres to No Code of Conduct. We are all adults. We accept anyone's contributions. Nothing else matters."

**Comment by domgetter** [comment]
>  and not in the CodeOfConduct file.

[It is in that file.](https://github.com/domgetter/NCoC/blob/5d5ebb0517aac3da3101f1bf28a2d1a788671db0/CODE_OF_CONDUCT.md)

**Comment by lil5** [comment]
@Karunamon then either the CoC should not contain a link to the Readme,
Or the Readme should be added in to the CoC.

**Comment by domgetter** [comment]
The CoC doesn't contain a link to the Readme, it contains a link to the repo.  It's just that the Readme is the file that comes up by default when you go to a repo on github.
