### ISSUE TITLE
Says to ban people you dont like, and censorship going on in your own project.

### ISSUE THREAD

**Issue by SilicaAndPina** [domgetter/NCoC#29]
Q: WTF, the discussion was locked, and/or I can't reply!?
Once again, we are not going to tolerate our community being overridden by the mob. If this starts to happen, we will nuke, delete, lock, close, ban, and do whatever we have to do to put the fire out. These discussions drag on and on and on, and they don't make communities better.

so here your saying we should "ban" so called "mobsters" 
what defines a "mobster" exactly?

also here https://github.com/domgetter/NCoC/issues/11 you changed the "fucked" to "*****" a very classic example of censorship right there.

**Comment by domgetter** [comment]
You're free to fork the project and/or make whatever code of conduct you like.
