### ISSUE TITLE
Anonymity

### ISSUE THREAD

**Issue by Blaisorblade** [domgetter/NCoC#3]
Hi!

> Unfortunately, if I were to tell people who I am, they would come after me personally, the projects I am involved with, and possibly get me even fired! I have a point to make, but I'm not stupid.

Friendly protip: if you really want this project to be anonymous, it shouldn't be in your personal GitHub account. (Create an organization for it, and remove your name from commits).
(And sorry for the screwup on Twitter — I was trying to send you a private message).

**Comment by domgetter** [comment]
Oh lol, that was from the copy-paste from the original at http://nocodeofconduct.com/

I'll take it out as it isn't relevant.  Also, no worries on the private message on Twitter.

Thanks!
